rootProject.name = "Digital Outlet Officer"
include(":app")
include(":core")
include(":navigation")
include(":feature_queue_passenger")
include(":feature_login")
include(":feature_splash")
include(":domain_user")
include(":feature_user_management")
include(":domain_location")
include(":feature_queue_fleet")
include(":domain_fleet")
include(":domain_passenger")
include(":feature_monitoring")
include(":feature:select_location")
