rootProject.name = "Digital Outlet Officer"
include(":app")
include(":core")
include(":navigation")
include(":feature:queue_passenger")
include(":feature:login")
include(":feature:splash")
include(":domain:user")
include(":feature:user_management")
include(":domain:location")
include(":feature:queue_fleet")
include(":domain:fleet")
include(":domain:passenger")
include(":feature:monitoring")
include(":feature:select_location")
include(":feature:qr_code")
include(":feature:airport_fleet")
